name := "mpv"
packages := "
mpv
"
base_images := "
quay.io/fedora/fedora-coreos:stable x86_64,aarch64
quay.io/fedora-ostree-desktops/silverblue:41
quay.io/fedora-ostree-desktops/kinoite:41
ghcr.io/ublue-os/aurora-dx:stable
ghcr.io/ublue-os/ucore:stable
ghcr.io/ublue-os/bazzite:stable
"

import '../sysext.just'

all: default
