name := "vk-hdr-layer"
packages := "
vk-hdr-layer
"
copr_repos := "jackgreiner/vk-hdr-layer"
base_images := "
quay.io/fedora/fedora-coreos:next
quay.io/fedora-ostree-desktops/kinoite:41
ghcr.io/ublue-os/aurora-dx:stable
ghcr.io/ublue-os/bazzite:stable
"

import '../sysext.just'

all: default
