dnf_arch := "i686 x86_64"
name := "vk-hdr-layer"
packages := "
vk-hdr-layer.x86_64
vk-hdr-layer.i686
"
copr_repos := "jackgreiner/vk-hdr-layer"
base_images := "
quay.io/fedora/fedora-coreos:next
quay.io/fedora-ostree-desktops/kinoite:41
ghcr.io/ublue-os/aurora-dx:stable
ghcr.io/ublue-os/bazzite:stable
ghcr.io/ublue-os/bazzite:41.20250216.2
"

import '../sysext.just'

all: default
