name := "ocp-sso-token"
packages := "
ocp-sso-token
"
copr_repos := "@cki/ocp-sso-token"
base_images := "
quay.io/fedora/fedora-coreos:next
quay.io/fedora-ostree-desktops/kinoite:41
ghcr.io/ublue-os/aurora-dx:stable
"

import '../sysext.just'

all: default
