name := "iotop"
packages := "iotop"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
ghcr.io/ublue-os/aurora-dx:stable
ghcr.io/ublue-os/ucore:stable
ghcr.io/ublue-os/bazzite:stable
"

import '../sysext.just'

all: default
