name := "fish"
packages := "fish"
base_images := "
quay.io/fedora-ostree-desktops/base-atomic:41 x86_64,aarch64
quay.io/fedora-ostree-desktops/base-atomic:42 x86_64,aarch64
quay.io/fedora/fedora-coreos:next
ghcr.io/ublue-os/ucore:stable
"

import '../sysext.just'

all: default
